# FLUENTD_ELASTICSEARCH_IP 的位置必須是 env/1 否則會替換掉錯誤的變數
- op: replace
  path: /spec/template/spec/containers/0/env/1
  value:
    name: "FLUENTD_ELASTICSEARCH_IP"
    value: "elasticsearch.$(POD_NAMESPACE)"
